# Generated by Django 2.2 on 2019-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_helloworld'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
