# Generated by Django 2.2 on 2019-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_helloworld_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='title',
            field=models.CharField(default='new title', max_length=250),
            preserve_default=False,
        ),
    ]
