# Generated by Django 2.2 on 2019-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_helloworld_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
