# Generated by Django 2.2 on 2019-06-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_helloworld_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Post Title'),
        ),
    ]
