# Generated by Django 2.2 on 2019-06-02 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_helloworld_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 8, 56, 26, 3981, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='helloworld',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
