# Generated by Django 2.2 on 2019-06-02 09:08

import blog.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190602_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='author_email',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[blog.models.typeemail, blog.models.typeemailfordot]),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 9, 8, 15, 45180, tzinfo=utc)),
        ),
    ]
