# Generated by Django 2.2 on 2019-06-02 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190602_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloworld',
            name='timetamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helloworld',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 12, 21, 44, 589177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helloworld',
            name='title',
            field=models.CharField(error_messages={'unique': 'This Post can be unique'}, help_text='Enter unique text', max_length=250, unique=True, verbose_name='Post Title'),
        ),
    ]
