# Generated by Django 2.2 on 2019-06-03 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190602_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helloworld',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 17, 7, 26, 847879, tzinfo=utc)),
        ),
    ]
